# Generated by Django 4.1.5 on 2023-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytimestamp', models.DateTimeField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
