# Generated by Django 4.1.5 on 2023-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingmodel', '0002_alter_bitcointracking_mytimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcointracking',
            name='mytimestamp',
            field=models.DateTimeField(default=1673615688),
        ),
    ]
