# Generated by Django 4.1.5 on 2023-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingmodel', '0006_alter_bitcointracking_mytimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcointracking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
